-- Maszyny Gliznowo - historia zmian maszyn i usuwanie zdjęć
-- Uruchom raz w Supabase SQL Editor.

create table if not exists public.machine_history (
  id bigint generated by default as identity primary key,
  machine_id bigint not null,
  action text not null,
  details text,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete set null
);

create index if not exists machine_history_machine_id_created_at_idx
  on public.machine_history (machine_id, created_at desc);

alter table public.machine_history enable row level security;

drop policy if exists "Authenticated users can read machine history" on public.machine_history;
create policy "Authenticated users can read machine history"
  on public.machine_history
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can insert machine history" on public.machine_history;
create policy "Authenticated users can insert machine history"
  on public.machine_history
  for insert
  to authenticated
  with check (true);

-- Polityka potrzebna do czyszczenia zdjęć przy trwałym usuwaniu maszyny.
-- Jeśli masz już własne polityki Storage, możesz zostawić tę zgodną z zalogowanymi użytkownikami.
drop policy if exists "Authenticated users can delete machine images" on storage.objects;
create policy "Authenticated users can delete machine images"
  on storage.objects
  for delete
  to authenticated
  using (bucket_id = 'machines');
